// packages/generator-svelte/src/components/Controls.svelte
<!-- @component
  Render one control group of `data-crudui-action` buttons.
-->
<script lang="ts">
  import type { ControlsVM } from '@crudui/generator-core';

  let { controls }: { controls: ControlsVM } = $props();
</script>

<div class="crudui-controls" role="group" aria-label={controls.label}>
  {#each controls.actions as action (action.name)}
    <button type="button" class="crudui-action" data-crudui-action={action.name} aria-label={action.label} disabled={action.disabled}></button>
  {/each}
</div>

// packages/generator-react/src/components/Controls.tsx
import * as React from 'react';
import type { ControlsVM } from '@crudui/generator-core';

/** Render one control group of `data-crudui-action` buttons. */
export function Controls({ controls }: { controls: ControlsVM }): React.ReactElement {
  return (
    <div className="crudui-controls" role="group" aria-label={controls.label}>
      {controls.actions.map((action) => (
        <button
          key={action.name}
          type="button"
          className="crudui-action"
          data-crudui-action={action.name}
          aria-label={action.label}
          disabled={action.disabled}
        />
      ))}
    </div>
  );
}
