// packages/generator-svelte/src/components/Field.svelte
<!--
  CRUDUI Svelte field dispatcher — the envelope, as a real `.svelte` element tree.

  Consumes one core `FieldViewModel` and builds the verified Limepie envelope:
  `.form-element-wrapper` (show=false → `style="display: none"`, DOM kept) >
  `<h6>` label (omitted for hidden) + `.description` + `.form-element` >
  `.input-group-wrapper[data-uniqid]` > widget. It dispatches the four field
  shapes (leaf / group / multiple-leaf|group / lang) plus the checkbox/switcher
  special envelope. Every envelope node is a real `.svelte` element; only the leaf
  CONTROL bytes are raw (Widget.svelte / widget.ts), injected at the container
  that owns them through `{@html}`.

  Appearance/visibility come pre-evaluated from the core's ResolvedDesign; this
  dispatcher only maps evaluated strings to class/style. svelte accepts a STRING
  `style` value verbatim (like Vue, no CSSProperties object). eval is never called.
-->
<script lang="ts">
  import type { FieldViewModel } from '@form-spec/generator-core';
  import Widget from './Widget.svelte';
  import Self from './Field.svelte';
  import { widgetRootRaw, rowButtonsHtml } from './widget';
  import {
    wrapperClass,
    wrapperStyle,
    inputGroupWrapperClass,
    langCodeSpan,
  } from './field';

  let { vm }: { vm: FieldViewModel } = $props();

  const wClass = $derived(wrapperClass(vm));
  const wStyle = $derived(wrapperStyle(vm));
  const igwClass = $derived(inputGroupWrapperClass(vm));
  const labelClass = $derived(vm.design.label.class);
  const labelStyle = $derived(vm.design.label.style?.trim());
  const showLabel = $derived(vm.label && !vm.omitLabel);
  const groupStyle = $derived(vm.groupStyle?.trim());

  // Single-field widget: a root-raw widget (bare/host-script/button/btn-group/
  // search) is serialized at the .input-group-wrapper root; else a real Widget.
  const leafRaw = $derived(vm.widget ? widgetRootRaw(vm.widget) : null);
</script>

{#snippet labelAndDescription()}
  {#if showLabel}
    <h6 class={labelClass || undefined} style={labelStyle || undefined}>{vm.label}</h6>
  {/if}
  {#if vm.description}
    <p class="description">{vm.description}</p>
  {/if}
{/snippet}

<!-- Row action buttons as REAL .svelte elements (plus/minus/copy/move). Used
     wherever the row container does not already inject its children via {@html}.
     The btn-group input-group-btn / btn-delete distinctions come from the core
     multiple settings; the empty text matches the fixture after normalization. -->
{#snippet rowButtons(s: { show: boolean; max?: number; copy?: boolean; sortable?: boolean })}
  {#if s.sortable}
    <!-- svelte-ignore a11y_consider_explicit_label -->
    <button type="button" class="btn btn-move-up"> </button>
    <!-- svelte-ignore a11y_consider_explicit_label -->
    <button type="button" class="btn btn-move-down"> </button>
  {/if}
  <!-- svelte-ignore a11y_consider_explicit_label -->
  <button type="button" class="btn btn-plus" data-multiple-max={s.max !== undefined ? String(s.max) : undefined}> </button>
  {#if s.copy}
    <!-- svelte-ignore a11y_consider_explicit_label -->
    <button type="button" class="btn btn-copy"> </button>
  {/if}
  <!-- svelte-ignore a11y_consider_explicit_label -->
  <button type="button" class={s.copy ? 'btn btn-minus btn-delete' : 'btn btn-minus'}> </button>
{/snippet}

{#if vm.shape === 'leaf' && vm.checkbox}
  <!-- checkbox / switcher special envelope. The checkbox input carries only
       non-empty/non-boolean attrs (class/name/type/value="1") → it renders
       correctly as a real element. -->
  <div class={wClass} name={vm.wrapperName} style={wStyle}>
    <div class="checkbox">
      <h6>
        <div class={igwClass} data-uniqid={vm.uniqid}>
          <div>
            <input class={vm.checkboxClass} name={vm.checkboxName} type="checkbox" value="1" />
            <span>{vm.label}</span>
          </div>
        </div>
      </h6>
      {#if vm.description}
        <p class="description">{vm.description}</p>
      {/if}
    </div>
  </div>
{:else if vm.shape === 'leaf'}
  <div class={wClass} name={vm.wrapperName} style={wStyle}>
    {@render labelAndDescription()}
    <div class="form-element">
      {#if leafRaw !== null}
        <div class={igwClass} data-uniqid={vm.uniqid}>{@html leafRaw}</div>
      {:else}
        <div class={igwClass} data-uniqid={vm.uniqid}>
          {#if vm.widget}<Widget w={vm.widget} />{/if}
        </div>
      {/if}
    </div>
  </div>
{:else if vm.shape === 'group'}
  <div class={wClass} name={vm.wrapperName} style={wStyle}>
    {@render labelAndDescription()}
    <div class="form-element">
      <div class={igwClass} data-uniqid={vm.uniqid}>
        <div class={vm.groupClass} style={groupStyle || undefined}>
          {#each vm.children ?? [] as child (child.path)}
            <Self vm={child} />
          {/each}
        </div>
      </div>
    </div>
  </div>
{:else if vm.shape === 'multiple-leaf'}
  <div class={wClass} name={vm.wrapperName} style={wStyle}>
    {@render labelAndDescription()}
    <div class="form-element">
      {#each vm.rows ?? [] as row (row.uniqid)}
        {@const rowRaw = row.widget ? widgetRootRaw(row.widget) : null}
        {#if rowRaw !== null}
          <!-- Root-raw control under the row wrapper → inject + buttons as
               siblings is impossible ({@html} owns children); buttons appended
               into the raw. -->
          <div class={row.wrapperClass} data-uniqid={row.uniqid}>{@html rowRaw + (vm.multiple ? rowButtonsHtml(vm.multiple) : '')}</div>
        {:else}
          <div class={row.wrapperClass} data-uniqid={row.uniqid}>
            {#if row.widget}<Widget w={row.widget} />{/if}
            {#if vm.multiple}{@render rowButtons(vm.multiple)}{/if}
          </div>
        {/if}
      {/each}
    </div>
  </div>
{:else if vm.shape === 'multiple-group'}
  <div class={wClass} name={vm.wrapperName} style={wStyle}>
    {@render labelAndDescription()}
    <div class="form-element">
      {#each vm.rows ?? [] as row (row.uniqid)}
        <div class={row.wrapperClass} data-uniqid={row.uniqid}>
          <div class={row.groupClass}>
            {#each row.children ?? [] as child (child.path)}
              <Self vm={child} />
            {/each}
          </div>
          <span class="btn-group input-group-btn">{#if vm.multiple}{@render rowButtons(vm.multiple)}{/if}</span>
        </div>
      {/each}
    </div>
  </div>
{:else if vm.shape === 'lang'}
  <div class={wClass} name={vm.wrapperName} style={wStyle}>
    {@render labelAndDescription()}
    <div class="form-element">
      <div class={igwClass} data-uniqid={vm.uniqid}>
        <div class={vm.lang?.groupClass}>
          {#if vm.lang?.title}
            <div class="lang-title">{vm.lang.title}</div>
          {/if}
          {#each vm.lang?.children ?? [] as child (child.code)}
            {@const childRaw = widgetRootRaw(child.widget)}
            {#if childRaw !== null}
              <div class="lang-child" data-lang={child.code}>{@html langCodeSpan(child.code) + childRaw}</div>
            {:else}
              <div class="lang-child" data-lang={child.code}>
                <span class="input-group-text lang-code">{child.code}</span>
                <Widget w={child.widget} />
              </div>
            {/if}
          {/each}
        </div>
      </div>
    </div>
  </div>
{/if}

// packages/generator-react/src/components/Field.tsx
/**
 * CRUDUI React field dispatcher — the envelope, as a real JSX tree.
 *
 * Consumes one core `FieldViewModel` and renders the verified limepie envelope:
 * `.form-element-wrapper` (show=false → style display:none, DOM kept) > `<h6>`
 * label (omitted for hidden) + `.description` + `.form-element` >
 * `.input-group-wrapper[data-uniqid]` > widget. It dispatches the four field
 * shapes (leaf / group / multiple-leaf|group / lang) plus the checkbox/switcher
 * special envelope. Every node is a JSX element — no string concatenation, no
 * dangerouslySetInnerHTML at the envelope level (only the leaf widgets use the
 * sanctioned RAW/script passthrough).
 *
 * Appearance/visibility come pre-evaluated from the core's ResolvedDesign; this
 * component only maps evaluated strings to className/style. eval is never called.
 */

import * as React from 'react';
import type { FieldViewModel, RowVM, WidgetModel, UnsupportedVM } from '@form-spec/generator-core';
import { Widget, widgetRootRaw } from './Widget';
import { styleObject } from './attrs';

type AnyWidget = WidgetModel | UnsupportedVM;

/** form-element-wrapper open: class+style from design.wrapper + show. */
function wrapperStyleObj(vm: FieldViewModel): React.CSSProperties | undefined {
  const hidden = vm.design.show ? '' : 'display: none';
  const extra = vm.design.wrapper.style?.trim() ?? '';
  const merged = [hidden, extra].filter((s) => s).join('; ');
  return styleObject(merged);
}

function wrapperClass(vm: FieldViewModel): string {
  return ['form-element-wrapper', vm.design.wrapper.class]
    .filter((s) => s && s.trim())
    .join(' ')
    .trim();
}

/** Shared props for the .form-element-wrapper open element. */
function wrapperProps(vm: FieldViewModel): Record<string, unknown> {
  const style = wrapperStyleObj(vm);
  return {
    className: wrapperClass(vm),
    name: vm.wrapperName,
    ...(style ? { style } : {}),
  };
}

function Label({ vm }: { vm: FieldViewModel }): React.ReactElement | null {
  if (!vm.label || vm.omitLabel) return null;
  const cls = vm.design.label.class;
  const style = styleObject(vm.design.label.style);
  return (
    <h6 {...(cls ? { className: cls } : {})} {...(style ? { style } : {})}>
      {vm.label}
    </h6>
  );
}

function Description({ vm }: { vm: FieldViewModel }): React.ReactElement | null {
  if (!vm.description) return null;
  return <p className="description">{vm.description}</p>;
}

/** Row action buttons (plus/minus/copy/move) from multiple settings. */
function RowButtons({ vm }: { vm: FieldViewModel }): React.ReactElement | null {
  const s = vm.multiple;
  if (!s) return null;
  const minusCls = s.copy ? 'btn btn-minus btn-delete' : 'btn btn-minus';
  return (
    <>
      {s.sortable ? (
        <>
          <button type="button" className="btn btn-move-up">
            {' '}
          </button>
          <button type="button" className="btn btn-move-down">
            {' '}
          </button>
        </>
      ) : null}
      <button
        type="button"
        className="btn btn-plus"
        {...(s.max !== undefined ? { 'data-multiple-max': String(s.max) } : {})}
      >
        {' '}
      </button>
      {s.copy ? (
        <button type="button" className="btn btn-copy">
          {' '}
        </button>
      ) : null}
      <button type="button" className={minusCls}>
        {' '}
      </button>
    </>
  );
}

/** input-group-wrapper for a single field (leaf/group/lang). */
function inputGroupWrapperClass(vm: FieldViewModel): string {
  return ['input-group-wrapper', vm.design.wrapper.class]
    .filter((s) => s && s.trim())
    .join(' ')
    .trim();
}

function CheckboxEnvelope({ vm }: { vm: FieldViewModel }): React.ReactElement {
  return (
    <div {...wrapperProps(vm)}>
      <div className="checkbox">
        <h6>
          <div className={inputGroupWrapperClass(vm)} data-uniqid={vm.uniqid}>
            <div>
              <input
                className={vm.checkboxClass}
                name={vm.checkboxName}
                type="checkbox"
                value="1"
              />
              <span>{vm.label}</span>
            </div>
          </div>
        </h6>
        <Description vm={vm} />
      </div>
    </div>
  );
}

/**
 * Render a widget into a sole-child container. A control whose only obstacle is
 * an opaque on* attr (datetime/host-script + behavior) is serialized raw at the
 * container root via widgetRootRaw, so no wrapper element is introduced. Every
 * other widget is a real JSX child.
 */
function WidgetContainer({
  w,
  className,
  uniqid,
}: {
  w: AnyWidget | undefined;
  className: string;
  uniqid: string;
}): React.ReactElement {
  if (w) {
    const raw = widgetRootRaw(w);
    if (raw !== null) {
      return (
        <div className={className} data-uniqid={uniqid} dangerouslySetInnerHTML={{ __html: raw }} />
      );
    }
  }
  return (
    <div className={className} data-uniqid={uniqid}>
      {w ? <Widget w={w} /> : null}
    </div>
  );
}

function LeafField({ vm }: { vm: FieldViewModel }): React.ReactElement {
  if (vm.checkbox) return <CheckboxEnvelope vm={vm} />;
  return (
    <div {...wrapperProps(vm)}>
      <Label vm={vm} />
      <Description vm={vm} />
      <div className="form-element">
        <WidgetContainer w={vm.widget} className={inputGroupWrapperClass(vm)} uniqid={vm.uniqid} />
      </div>
    </div>
  );
}

function GroupField({ vm }: { vm: FieldViewModel }): React.ReactElement {
  return (
    <div {...wrapperProps(vm)}>
      <Label vm={vm} />
      <Description vm={vm} />
      <div className="form-element">
        <div className={inputGroupWrapperClass(vm)} data-uniqid={vm.uniqid}>
          <div
            className={vm.groupClass}
            {...(styleObject(vm.groupStyle) ? { style: styleObject(vm.groupStyle) } : {})}
          >
            {(vm.children ?? []).map((c, i) => (
              <Field key={i} vm={c} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

function MultipleLeafRow({ row, vm }: { row: RowVM; vm: FieldViewModel }): React.ReactElement {
  return (
    <div className={row.wrapperClass} data-uniqid={row.uniqid}>
      {row.widget ? <Widget w={row.widget} /> : null}
      <RowButtons vm={vm} />
    </div>
  );
}

function MultipleLeafField({ vm }: { vm: FieldViewModel }): React.ReactElement {
  return (
    <div {...wrapperProps(vm)}>
      <Label vm={vm} />
      <Description vm={vm} />
      <div className="form-element">
        {(vm.rows ?? []).map((row, i) => (
          <MultipleLeafRow key={i} row={row} vm={vm} />
        ))}
      </div>
    </div>
  );
}

function MultipleGroupRow({ row, vm }: { row: RowVM; vm: FieldViewModel }): React.ReactElement {
  return (
    <div className={row.wrapperClass} data-uniqid={row.uniqid}>
      <div className={row.groupClass}>
        {(row.children ?? []).map((c, i) => (
          <Field key={i} vm={c} />
        ))}
      </div>
      <span className="btn-group input-group-btn">
        <RowButtons vm={vm} />
      </span>
    </div>
  );
}

function MultipleGroupField({ vm }: { vm: FieldViewModel }): React.ReactElement {
  return (
    <div {...wrapperProps(vm)}>
      <Label vm={vm} />
      <Description vm={vm} />
      <div className="form-element">
        {(vm.rows ?? []).map((row, i) => (
          <MultipleGroupRow key={i} row={row} vm={vm} />
        ))}
      </div>
    </div>
  );
}

function LangField({ vm }: { vm: FieldViewModel }): React.ReactElement {
  const lang = vm.lang!;
  return (
    <div {...wrapperProps(vm)}>
      <Label vm={vm} />
      <Description vm={vm} />
      <div className="form-element">
        <div className={inputGroupWrapperClass(vm)} data-uniqid={vm.uniqid}>
          <div className={lang.groupClass}>
            {lang.title ? <div className="lang-title">{lang.title}</div> : null}
            {lang.children.map((c, i) => (
              <div key={i} className="lang-child" data-lang={c.code}>
                <span className="input-group-text lang-code">{c.code}</span>
                <Widget w={c.widget} />
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

/** Dispatch one field view model to its shape component. */
export function Field({ vm }: { vm: FieldViewModel }): React.ReactElement {
  switch (vm.shape) {
    case 'group':
      return <GroupField vm={vm} />;
    case 'multiple-leaf':
      return <MultipleLeafField vm={vm} />;
    case 'multiple-group':
      return <MultipleGroupField vm={vm} />;
    case 'lang':
      return <LangField vm={vm} />;
    case 'leaf':
    default:
      return <LeafField vm={vm} />;
  }
}
