// packages/generator-react/src/components/Detail.tsx
/** CRUDUI React read-only detail component backed by the shared DetailViewModel. */

import * as React from 'react';
import type { DetailViewModel, DetailFieldVM } from '@polyspec/crudui-generator-core';
import { CellBody } from './Cell';
import { styleObject } from './attrs';
import { RawContainer } from './raw';
import { Toolbar } from './List';

function fieldClass(field: DetailFieldVM): string | undefined {
  return ['crudui-detail__value', 'crudui-value', `crudui-value--${field.format.type}`, field.design.main.class]
    .filter((value) => value && value.trim()).join(' ') || undefined;
}

function Field({ field }: { field: DetailFieldVM }): React.ReactElement {
  const display = field.display;
  const valueProps = {
    className: fieldClass(field),
    style: styleObject(field.design.main.style),
  };
  return (
    <div className="crudui-detail__field">
      <dt className="crudui-detail__label">{field.label}</dt>
      {typeof display !== 'string' && display.kind === 'html' ? (
        <RawContainer tag="dd" {...valueProps} html={display.html} />
      ) : (
        <dd {...valueProps}><CellBody cell={field} /></dd>
      )}
    </div>
  );
}

/**
 * Render an evaluated read-only detail model without data access or evaluation: the actions,
 * when the detail has any, and the definition list.
 */
export function Detail({ vm }: { vm: DetailViewModel }): React.ReactElement {
  const className = ['crudui-detail', vm.design.wrapper.class].filter((value) => value && value.trim()).join(' ') || undefined;
  return (
    <>
      <Toolbar actions={vm.actions} block="crudui-detail" />
      <dl className={className} style={styleObject(vm.design.wrapper.style)}>{vm.fields.map((field) => <Field key={field.key} field={field} />)}</dl>
    </>
  );
}

// packages/generator-svelte/src/components/Detail.svelte
<!-- @component
  Render an evaluated read-only detail model with shared CRUDUI display cells: the actions, when
  the detail has any, and the definition list.
-->
<script lang="ts">
  import type { DetailViewModel, DetailFieldVM, CellDisplay } from '@polyspec/crudui-generator-core';
  import { patched, firstMarkup } from './raw.js';
  import Actions from './Actions.svelte';

  let { vm }: { vm: DetailViewModel } = $props();
  const wrapperClass = $derived(['crudui-detail', vm.design.wrapper.class].filter((s) => s && s.trim()).join(' ').trim());
  const wrapperStyle = $derived(vm.design.wrapper.style?.trim() || undefined);
  const valueClass = (field: DetailFieldVM) => ['crudui-detail__value', 'crudui-value', `crudui-value--${field.format.type}`, field.design.main.class].filter((s) => s && s.trim()).join(' ').trim();
</script>

{#snippet cellDisplay(display: CellDisplay)}
  {#if typeof display === 'string'}
    {display}
  {:else if display.kind === 'badge'}
    <span class="crudui-badge" data-crudui-variant={display.variant || undefined}>{display.label}</span>
  {:else if display.kind === 'link'}
    <a href={display.href} target={display.target ?? undefined}>{display.text}</a>
  {:else if display.kind === 'image'}
    <img src={display.src} alt={display.alt} width={display.width ?? undefined} height={display.height ?? undefined} />
  {:else if display.kind === 'bool'}
    {#if display.as === 'check'}
      <span class="crudui-bool crudui-bool--check" data-crudui-state={String(display.value)} aria-label={display.label}>{display.value ? '✔' : '✘'}</span>
    {:else if display.as === 'icon'}
      <span class="crudui-bool crudui-bool--icon" data-crudui-state={String(display.value)} aria-label={display.label}></span>
    {:else}
      <span class="crudui-bool crudui-bool--text" data-crudui-state={String(display.value)}>{display.label}</span>
    {/if}
  {/if}
{/snippet}

<Actions actions={vm.actions} block="crudui-detail" />
<dl class={wrapperClass} style={wrapperStyle}>
  {#each vm.fields as field (field.key)}
    <div class="crudui-detail__field">
      <dt class="crudui-detail__label">{field.label}</dt>
      {#if typeof field.display !== 'string' && field.display.kind === 'html'}{@const html = field.display.html}
        <!-- eslint-disable-next-line svelte/no-at-html-tags -- the `html` field format declares raw HTML. -->
        <dd class={valueClass(field)} style={field.design.main.style?.trim() || undefined} {@attach patched(html)}>{@html firstMarkup(() => html)}</dd>
      {:else}
        <dd class={valueClass(field)} style={field.design.main.style?.trim() || undefined}>{@render cellDisplay(field.display)}</dd>
      {/if}
    </div>
  {/each}
</dl>
