// packages/generator-react/src/components/Form.tsx
/**
 * CRUDUI React form component — `<Form>` renders the composed field list.
 *
 * It takes the core's already-built `FieldViewModel[]` (compose + design eval +
 * i18n + tree) and maps each top-level field to a `<Field>` inside the
 * `.form-group` envelope. It is a pure presentational tree: no evaluation, no
 * string concatenation, no completed-HTML echo. SSR via react-dom/server in the
 * `renderForm` entry produces the legacy envelope byte-compatibly after
 * normalization.
 */

import * as React from 'react';
import type { FieldViewModel } from '@form-spec/generator-core';
import { Field } from './Field';

/** Props for the CRUDUI form: the core-built top-level field view models. */
export interface FormProps {
  fields: FieldViewModel[];
}

/** Render the `.form-group` envelope around the top-level fields. */
export function Form({ fields }: FormProps): React.ReactElement {
  return (
    <div className="form-group">
      {fields.map((vm, i) => (
        <Field key={i} vm={vm} />
      ))}
    </div>
  );
}

// packages/generator-svelte/src/components/Form.svelte
<!--
  CRUDUI Svelte form renderer — `Form` builds the composed field list as a real
  `.svelte` element tree.

  It takes the core's already-built `FieldViewModel[]` (compose + design eval +
  i18n + tree) and maps each top-level field to a `Field` element inside the
  `.form-group` envelope. A pure presentational `.svelte` tree: no evaluation, no
  string concatenation, no completed-form HTML echo. SSR via svelte/server
  render() produces the legacy envelope byte-compatibly after normalization.
-->
<script lang="ts">
  import type { FieldViewModel } from '@crudui/generator-core';
  import Field from './Field.svelte';

  let { fields }: { fields: FieldViewModel[] } = $props();
</script>

<div class="form-group">
  {#each fields as vm (vm.path)}
    <Field {vm} />
  {/each}
</div>
