// packages/generator-react/src/components/FormSessionView.tsx
import * as React from 'react';
import { connectForm, type FormSession } from '@crudui/generator-core';
import { Field } from './Field';

/** An interactive form whose structure can be prepared and cached before data arrives. */
export function FormSessionView({ session }: { session: FormSession }): React.ReactElement {
  const snapshot = React.useSyncExternalStore(session.subscribe, session.getSnapshot, session.getSnapshot);
  const root = React.useRef<HTMLDivElement>(null);
  const binding = React.useRef<ReturnType<typeof connectForm> | null>(null);
  React.useLayoutEffect(() => {
    binding.current = connectForm(root.current!, session);
    return () => { binding.current?.disconnect(); binding.current = null; };
  }, [session]);
  React.useLayoutEffect(() => { binding.current?.sync(); }, [snapshot]);
  return <div className="form-group" ref={root}>
    {snapshot.fields.map(vm => <Field key={vm.path} vm={vm} />)}
  </div>;
}

// packages/generator-svelte/src/components/FormSessionView.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { connectForm, type FormSession } from '@crudui/generator-core';
  import Field from './Field.svelte';

  let { session }: { session: FormSession } = $props();
  let root: HTMLDivElement;
  let snapshot = $state(untrack(() => session.getSnapshot()));
  let binding: ReturnType<typeof connectForm> | undefined;

  $effect(() => {
    const current = session;
    snapshot = current.getSnapshot();
    const unsubscribe = current.subscribe(() => { snapshot = current.getSnapshot(); });
    binding = connectForm(root, current);
    return () => { binding?.disconnect(); unsubscribe(); };
  });
  $effect(() => { snapshot; binding?.sync(); });
</script>

<div class="form-group" bind:this={root}>
  {#each snapshot.fields as vm (vm.path)}
    <Field {vm} />
  {/each}
</div>
